#!/usr/bin/env python3
"""Run fixtures and write docs/benchmark.md plus a demo transcript."""

from __future__ import annotations

import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from commit_delta.engine import Engine, EngineConfig  # noqa: E402
from commit_delta.parse import capture_snapshot  # noqa: E402
from commit_delta.report import format_report  # noqa: E402
from commit_delta.worktree import IsolatedTree  # noqa: E402
from tests.support.builders import (  # noqa: E402
    build_demo,
    build_fixture_a,
    build_fixture_b,
    build_fixture_c,
    build_fixture_d,
    build_fixture_dense,
    build_fixture_e,
    build_fixture_messy,
)


def run_one(name: str, builder, dest: Path, confirm: int = 1) -> dict:
    repo = builder(dest)
    snap = capture_snapshot(repo)
    t0 = time.monotonic()
    with IsolatedTree(repo) as tree:
        engine = Engine(
            snap,
            tree,
            EngineConfig(command=["./reproduce.sh"], timeout=15.0, confirm=confirm),
        )
        result = engine.reduce()
        patch = engine
    elapsed = time.monotonic() - t0
    ids = [h.id for h in result.minimal]
    return {
        "name": name,
        "result": result,
        "ids": ids,
        "elapsed": elapsed,
        "report": format_report(result),
        "patch_text": __import__(
            "commit_delta.apply", fromlist=["render_patch"]
        ).render_patch(result.minimal),
    }


def main() -> int:
    out_dir = ROOT / "docs"
    out_dir.mkdir(exist_ok=True)
    scratch = ROOT / ".bench-scratch"
    if scratch.exists():
        import shutil

        shutil.rmtree(scratch)
    scratch.mkdir()

    cases = [
        ("A single bad hunk", build_fixture_a, 1),
        ("B interacting pair", build_fixture_b, 1),
        ("C invalid subsets", build_fixture_c, 1),
        ("D multiple minima", build_fixture_d, 1),
        ("E confirm=3", build_fixture_e, 3),
        ("F messy refactor", build_fixture_messy, 1),
        ("G dense interacting", build_fixture_dense, 1),
        ("demo 400+ lines", build_demo, 1),
    ]
    rows = []
    demo_report = ""
    demo_patch = ""
    messy_report = ""
    for name, builder, confirm in cases:
        slug = name.split()[0].lower()
        data = run_one(name, builder, scratch / slug, confirm=confirm)
        r = data["result"]
        rows.append(data)
        if name.startswith("demo"):
            demo_report = data["report"]
            demo_patch = data["patch_text"]
        if name.startswith("F "):
            messy_report = data["report"]
        print(f"{name}: {data['ids']} in {data['elapsed']:.2f}s")

    lines = [
        "# Benchmark",
        "",
        "Generated by `scripts/bench.py` on this machine. Numbers are",
        "candidate evaluations of tiny Python fixtures, not a production",
        "test suite.",
        "",
        "| Fixture | Input hunks | Input lines | Output hunks | Output lines | Trials | PASS | FAIL | UNRESOLVED | Cache | Seconds |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for data in rows:
        s = data["result"].stats
        lines.append(
            f"| {data['name']} | {s.input_hunks} | {s.input_lines} | "
            f"{s.output_hunks} | {s.output_lines} | {s.trials} | "
            f"{s.pass_n} | {s.fail_n} | {s.unresolved_n} | {s.cache_hits} | "
            f"{s.elapsed_s:.2f} |"
        )
    lines.extend(
        [
            "",
            "## Reduction ratio",
            "",
            "The original demo is the easy shape: noise in other files,",
            "one tiny operator flip. Fixture F is the harder one: a fat",
            "fused rewrite plus a new module, with a naive reproduce",
            "script that does **not** use exit 125.",
            "",
            "## Demo report",
            "",
            "```",
            demo_report.rstrip(),
            "```",
            "",
            "## Demo reduced patch",
            "",
            "```diff",
            demo_patch.rstrip(),
            "```",
            "",
            "## Fixture F — messy refactor",
            "",
            "```",
            messy_report.rstrip(),
            "```",
            "",
            "## Follow-up notes",
            "",
            "- Fixture F reproduce.sh does **not** map import errors to 125.",
            "  3 trials were UNRESOLVED via the Python traceback heuristic.",
            "  `--strict-exits` on the same tree reduces to `checkout.py` only",
            "  (an ImportError, not the assertion). That is the poison the",
            "  heuristic exists to prevent.",
            "- The leftover checkout hunk is fat (~23 lines). The off-by-one",
            "  sits in the middle of a contiguous rewrite; hunk-level cannot",
            "  extract the single `- 1`. That is the v0.1 ceiling, reported",
            "  honestly.",
            "- Fixture G keeps all 4 required bits and drops noise. Reduction",
            "  can be real without being dramatic.",
            "",
        ]
    )
    (out_dir / "benchmark.md").write_text("\n".join(lines), encoding="utf-8")
    (out_dir / "demo-report.txt").write_text(demo_report, encoding="utf-8")
    print("wrote", out_dir / "benchmark.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
